from typing import Any, Protocol


class LLMProvider(Protocol):
    model: str

    def generate(self, prompt: str, system: str = "") -> str: ...

    def chat(self, messages: list[dict[str, str]], system: str = "", response_format: dict[str, Any] | str | None = None) -> str: ...

    def structured_output(self, messages: list[dict[str, str]], schema: dict[str, Any]) -> dict[str, Any]: ...

    def tool_calling(self, messages: list[dict[str, str]], tools: list[dict[str, Any]]) -> dict[str, Any]: ...

    def embed(self, texts: list[str]) -> list[list[float]]: ...
